modpack-versions = "2.0.6"
#This should be your Modpacks Curseforge Page, not the Versions page (this is not synced to the client if different on server)
curseforge-url = "https://www.curseforge.com/minecraft/modpacks/darkrpg-forge"
#This should be your Modpacks Modrinth Page, not the Versions page (this is not synced to the client if different on server)
modrinth-url = ""

